apiVersion: v2
name: it-tools
description: Collection of handy online tools for developers, with great UX
icon: https://github.com/sharevb/it-tools/blob/ecdf2c1803ef4c9058db4a66b559e913f09f5a77/public/mstile-310x310.png
sources:
  - https://github.com/jeffresc/charts
  - https://github.com/sharevb/it-tools
maintainers:
  - name: Jeff Rescignano
    email: jeff@jeffresc.dev

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2026.1.4" # renovate: image=ghcr.io/sharevb/it-tools
