{{- if and (not .Values.govee.existingSecret) (or .Values.govee.email .Values.govee.password .Values.govee.apiKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "govee2mqtt.fullname" . }}
  labels:
    {{- include "govee2mqtt.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.govee.email }}
  govee-email: {{ .Values.govee.email | b64enc | quote }}
  {{- end }}
  {{- if .Values.govee.password }}
  govee-password: {{ .Values.govee.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.govee.apiKey }}
  govee-api-key: {{ .Values.govee.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.mqtt.user }}
  mqtt-user: {{ .Values.mqtt.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.mqtt.password }}
  mqtt-password: {{ .Values.mqtt.password | b64enc | quote }}
  {{- end }}
{{- end }}
