apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt
  template:
    metadata:
      labels:
        app: newt
    spec:
      containers:
        - name: newt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: PANGOLIN_ENDPOINT
              value: "{{ .Values.pangolin.endpoint }}"
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: "{{ .Values.secret.id.key }}"
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: "{{ .Values.secret.secret.key}}"
