# Default values for manyfold.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global parameters
# -- Number of replicas of the manyfold Deployment
replicaCount: 1

## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## NOTE: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set
##
# -- Affinity for pod assignment
affinity: {}
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
##
# -- Node labels for pod assignment
nodeSelector: {}
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
# -- Tolerations for pod assignment
tolerations: []

# -- Additional annotations for the Pod resource
podAnnotations: {}
# -- Additional labels for the Pod resource
podLabels: {}

# -- Docker registry pull secrets
imagePullSecrets: []
# -- Name override
nameOverride: ""
# -- Full name override
fullnameOverride: ""

## Image parameters
image:
  # -- Container image repository
  repository: ghcr.io/manyfold3d/manyfold
  # -- Container image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion
  tag: ""

## Service account parameters
serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Additional annotations for the ServiceAccount resource
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

## Pod security context parameters
# -- Additional pod security context
podSecurityContext: {}
  # fsGroup: 2000

## Security context parameters
# -- Container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## Service parameters
service:
  # -- Service type to create
  type: ClusterIP
  # -- Service port to use
  port: 3214

## Ingress parameters
## Configure the ingress resource that allows you to access the application
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  # -- Enable ingress record generation
  enabled: false
  # -- IngressClass that will be used to implement the Ingress
  className: ""
  # -- Additional annotations for the Ingress resource
  annotations: {}
  # -- An array with hostname(s) to be covered with the ingress record
  hosts: []
  # -- TLS configuration for hostname(s) to be covered with this ingress record
  tls: []

## Resources parameters
resources: {}

## Probe parameters
livenessProbe:
  httpGet:
    # -- HTTP path for the liveness probe
    path: /health
    # -- Port name or number for the liveness probe
    port: http
readinessProbe:
  httpGet:
    # -- HTTP path for the readiness probe
    path: /health
    # -- Port name or number for the readiness probe
    port: http

## Autoscaling parameters
## Autoscaling parameters
## ref: https://kubernetes.io/docs/concepts/workloads/autoscaling/
##
autoscaling:
  # -- Enable Horizontal POD autoscaling
  enabled: false
  # -- Minimum number of replicas
  minReplicas: 1
  # -- Maximum number of replicas
  maxReplicas: 100
  # -- Target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## Extra volumes parameter
## Additional volumes on the Deployment definition
# -- Provide extra volumes for the main pod
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

## Extra volume mounts parameter
## Additional volume mounts for the Deployment
# -- Additional volume mounts for the main pod
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true


## Valkey parameters
valkey:
  # -- Deploy Valkey chart
  enabled: false
  # -- Valkey architecture
  architecture: standalone
  auth:
    # -- Enable Valkey authentication
    enabled: false

## PostgreSQL parameters
postgresql:
  # -- Deploy PostgreSQL chart
  enabled: false
  global:
    postgresql:
      auth:
        # -- Database username
        username: manyfold
        # -- Database name
        database: manyfold
        # -- Database password
        password: manyfold

## Environment parameters
env:
  SECRET_KEY_BASE:
    value: "super_secret_key"
  REDIS_URL:
    value: redis://{{ printf "%s-valkey-primary" .Release.Name }}:6379/1
  DATABASE_ADAPTER:
    value: "postgresql"
  DATABASE_HOST:
    value: "{{ .Release.Name }}-postgresql"
  DATABASE_PORT:
    value: "5432"
  DATABASE_USER:
    value: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  # -- You should provide your own secret outside of this helm-chart and use `postgresql.global.postgresql.auth.existingSecret` to provide credentials to the postgresql instance
  DATABASE_PASSWORD:
    value: "{{ .Values.postgresql.global.postgresql.auth.password }}"
  DATABASE_NAME:
    value: "{{ .Values.postgresql.global.postgresql.auth.database }}"

## Persistence parameters
persistence:
  # -- If persistence is enabled
  enabled: false
  # -- Persistent storage PVC name
  name: "manyfold-library"
  # -- Mount path
  mountPath: "/manyfold-library"
  # -- Persistent storage PVC storage class
  storageClass: ""
  # -- Persistent storage PVC size
  size: "10Gi"

## Init containers parameter
# -- Provide init containers for the main pod
initContainers: []
