# Default values for esphome.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Global parameters
## @param replicaCount Number of replicas of the ESPHome StatefulSet
replicaCount: 1

## @param affinity Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## NOTE: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set
##
affinity: {}
## @param nodeSelector Node labels for pod assignment
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
##
nodeSelector: {}
## @param tolerations Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## @param podAnnotations Additional annotations for the Pod resource
## @param podLabels Additional labels for the Pod resource
podAnnotations: {}
podLabels: {}

## @param imagePullSecrets Docker registry pull secrets
## @param nameOverride Name override
## @param fullnameOverride Full name override
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## @section Image parameters
## @param image.repository Docker image repository
## @param image.pullPolicy Docker image pull policy
## @param image.tag Overrides the image tag whose default is the chart appVersion
image:
  repository: ghcr.io/esphome/esphome
  pullPolicy: IfNotPresent
  tag: ""

## @section Service account parameters
## @param serviceAccount.create Specifies whether a service account should be created
## @param serviceAccount.automount Automatically mount a ServiceAccount's API credentials?
## @param serviceAccount.annotations Additional annotations for the ServiceAccount resource
## @param serviceAccount.name The name of the service account to use. If not set and create is true, a name is generated using the fullname template
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

## @section Pod security context parameters
## @param podSecurityContext.runAsUser User to run pod as
## @param podSecurityContext.fsGroup Group to mount volumes in as
podSecurityContext:
  runAsUser: 10099
  fsGroup: 10099

## @section Security context parameters
## @param securityContext.capabilities.drop Capabilities to drop
## @param securityContext.readOnlyRootFilesystem If root filesystem should be read-only
## @param securityContext.runAsNonRoot If pod should be run as non-root
## @param securityContext.runAsUser User to run pod as
## @param securityContext.runAsGroup Group to run pod as
## @param securityContext.allowPrivilegeEscalation If privilege escalation should be allowed
## @param securityContext.seccompProfile.type seccomp profile type
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10099
  runAsGroup: 10099
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

## @section Service parameters
## @param service.type Service type to create
## @param service.port Service port to use
service:
  type: ClusterIP
  port: 6052

## @section Ingress parameters
## Configure the ingress resource that allows you to access the Apache installation
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
## @param ingress.enabled Enable ingress record generation
## @param ingress.className IngressClass that will be be used to implement the Ingress
## @param ingress.annotations Additional annotations for the Ingress resource
## @param ingress.hosts An array with hostname(s) to be covered with the ingress record
## @param ingress.tls TLS configuration for hostname(s) to be covered with this ingress record
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

## @section Resources parameters
## @param resources.requests.cpu Minimum CPU requested
## @param resources.requests.memory Minimum memory requested
## @extra resources.limits.cpu Maximum CPU allowed
## @extra resources.limits.memory Maximum memory allowed
resources:
  requests:
    cpu: 10m
    memory: 128Mi

## @section Autoscaling parameters
## Autoscaling parameters
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
## @param autoscaling.enabled Enable Horizontal POD autoscaling
## @param autoscaling.minReplicas Minimum number of replicas
## @param autoscaling.maxReplicas Maximum number of replicas
## @param autoscaling.targetCPUUtilizationPercentage Target CPU utilization percentage
## @param autoscaling.targetMemoryUtilizationPercentage Target Memory utilization percentage
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

## @section Persistence parameters
## @param persistence.enabled If persistence is enabled
## @param persistence.name Persistent storage PVC name
## @param persistence.storageClass Persistent storage PVC storage class
## @param persistence.size Persistent storage PVC size
persistence:
  enabled: false
  name: "esphome-config"
  storageClass: "my-storageclass"
  size: "5Gi"
