name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Get Changed Charts
        id: changed-charts
        run: |
          CHANGED_CHARTS=()
          for chart in charts/*; do
            if [ -d "$chart" ] && git diff --quiet HEAD~1 -- "$chart"; then
              CHANGED_CHARTS+=("$chart")
            fi
          done
          echo "changed=$(IFS=,; echo "${CHANGED_CHARTS[*]}")" >> $GITHUB_ENV

      - name: Package Changed Helm Charts
        if: env.changed != ''
        run: |
          mkdir -p helm-charts
          for chart in $(echo "$changed" | tr ',' ' '); do
            helm package "$chart" --destination helm-charts/
          done

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Helm Charts to Release
        if: env.changed != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for chart in $(echo "$changed" | tr ',' ' '); do
            CHART_NAME=$(basename "$chart")
            RELEASE_VERSION=$(jq -r ".\"charts/$CHART_NAME\"" < .release-please-manifest.json)
            echo "Uploading $CHART_NAME version $RELEASE_VERSION..."
            gh release upload "v$RELEASE_VERSION" helm-charts/"$CHART_NAME-$RELEASE_VERSION.tgz"
          done


      - name: Publish Helm Charts to `gh-pages`
        if: env.changed != ''
        run: |
          # Clone the gh-pages branch
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }}.git gh-pages
          cd gh-pages

          # Move packaged charts to gh-pages
          mv ../helm-charts/* .

          # Update Helm index.yaml
          helm repo index . --url https://your-github-username.github.io/your-repo/

          # Commit and push changes
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish new Helm charts"
          git push origin gh-pages
