name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: helm
          monorepo-tags: true
          packages: |
            charts/esphome/Chart.yaml
            charts/it-tools/Chart.yaml
